### ISSUE TITLE
Why alpha=0 after many iterations, making gap not decrease in FW method?

### ISSUE THREAD

**Issue by yuzhenfeng2002** [MatteoBettini/Traffic-Assignment-Frank-Wolfe-2021#3]
I run the code with parameters
```
computeAssingment(net_file=net_file,
                                     algorithm="FW",
                                     costFunction=BPRcostFunction,
                                     systemOptimal=False,
                                     verbose=True,
                                     accuracy=0.000001,
                                     maxIter=500,
                                     maxTime=6000000)
```
in `sioux_falls_net_file` network. However, I found that after about 160 iterations, alpha is always 0, thus the flow is not updated, making the gap not decrease anymore.

How to solve the problem?

The following figure shows the gap of each iteration, with vertical line being log(gap).

<img width="601" alt="image" src="https://github.com/matteobettini/Traffic-Assignment-Frank-Wolfe-2021/assets/61533778/dd5f8150-465c-47ea-8c0a-7a29cf456358">

**Comment by matteobettini** [comment]
Mh haven't used this in years but the sioux falls results had been checked.

After those iterations have you converged to the correct user equilibrium flows?
It might be impossible to achieve a smaller gap

**Comment by yuzhenfeng2002** [comment]
Dear Bettini, I've found the bugs and pulled requests to fix them. You can merge it.
